/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultRouteImport } from './routes/result'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as QuizTopicIdRouteImport } from './routes/quiz.$topicId'
import { Route as SubjectsSubjectIdIndexRouteImport } from './routes/subjects.$subjectId.index'
import { Route as SubjectsSubjectIdChapterIdRouteImport } from './routes/subjects.$subjectId.$chapterId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTopicIdRoute = QuizTopicIdRouteImport.update({
  id: '/quiz/$topicId',
  path: '/quiz/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdIndexRoute = SubjectsSubjectIdIndexRouteImport.update({
  id: '/subjects/$subjectId/',
  path: '/subjects/$subjectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdChapterIdRoute =
  SubjectsSubjectIdChapterIdRouteImport.update({
    id: '/subjects/$subjectId/$chapterId',
    path: '/subjects/$subjectId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/quiz/$topicId': typeof QuizTopicIdRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$subjectId/$chapterId': typeof SubjectsSubjectIdChapterIdRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/quiz/$topicId': typeof QuizTopicIdRoute
  '/subjects': typeof SubjectsIndexRoute
  '/subjects/$subjectId/$chapterId': typeof SubjectsSubjectIdChapterIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/result': typeof ResultRoute
  '/settings': typeof SettingsRoute
  '/quiz/$topicId': typeof QuizTopicIdRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$subjectId/$chapterId': typeof SubjectsSubjectIdChapterIdRoute
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/result'
    | '/settings'
    | '/quiz/$topicId'
    | '/subjects/'
    | '/subjects/$subjectId/$chapterId'
    | '/subjects/$subjectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/result'
    | '/settings'
    | '/quiz/$topicId'
    | '/subjects'
    | '/subjects/$subjectId/$chapterId'
    | '/subjects/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/home'
    | '/onboarding'
    | '/result'
    | '/settings'
    | '/quiz/$topicId'
    | '/subjects/'
    | '/subjects/$subjectId/$chapterId'
    | '/subjects/$subjectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  ResultRoute: typeof ResultRoute
  SettingsRoute: typeof SettingsRoute
  QuizTopicIdRoute: typeof QuizTopicIdRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  SubjectsSubjectIdChapterIdRoute: typeof SubjectsSubjectIdChapterIdRoute
  SubjectsSubjectIdIndexRoute: typeof SubjectsSubjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$topicId': {
      id: '/quiz/$topicId'
      path: '/quiz/$topicId'
      fullPath: '/quiz/$topicId'
      preLoaderRoute: typeof QuizTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/': {
      id: '/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof SubjectsSubjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/$chapterId': {
      id: '/subjects/$subjectId/$chapterId'
      path: '/subjects/$subjectId/$chapterId'
      fullPath: '/subjects/$subjectId/$chapterId'
      preLoaderRoute: typeof SubjectsSubjectIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  ResultRoute: ResultRoute,
  SettingsRoute: SettingsRoute,
  QuizTopicIdRoute: QuizTopicIdRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  SubjectsSubjectIdChapterIdRoute: SubjectsSubjectIdChapterIdRoute,
  SubjectsSubjectIdIndexRoute: SubjectsSubjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
